__base__:
    - ../../default_runtime.yaml
    - ../../schedules/schedule_5e.yaml
    - ../../datasets/hint/hint_phase_III_cos_schedule_augment.yaml
    - ../../models/mmcto/mmcto_summarization-no-table_augment_aux-loss-share-fc_moe-concat.yaml
