__base__:
    - ../../default_runtime.yaml
    - ../../schedules/schedule_5e.yaml
    - ../../datasets/hint/hint_phase_III_cos_schedule.yaml
    - ../../models/mmcto/mmcto_moe-concat.yaml

model:
    init_args:
        model:
            init_args:
                final_input_parts: [summarization, smiless, description]
