__base__:
    - ../../../default_runtime.yaml
    - ../../../schedules/schedule_5e.yaml
    - ../../../datasets/hint/hint_phase_I_cos_schedule_augment.yaml
    - ../../../models/mmcto/pretrain/mmcto_summarization-no-table_augment_aux-loss_load-pretrained-ckpt.yaml
