__base__: ../base/mmcto.yaml

model:
    init_args:
        model:
            init_args:
                final_input_parts: [
                        # summarization,
                        # description,
                        criteria,
                        diseases,
                        drugs,
                        # smiless_concat,
                        # smiless_transformer_concat,
                    ]

data:
    init_args:
        dataset_cfg:
            fit:
                init_args:
                    input_parts: [
                            # summarization,
                            # description,
                            criteria,
                            diseases,
                            drugs,
                            # smiless,
                            # smiless_transformer_concat,
                        ]
