__base__: ../base/mmcto_summarization-drugs-diseases-criteria-only_diseases_augment-cos-loss_aux-loss.yaml

trainer:
    logger:
        init_args:
            tags:
                pre_item: mmcto_augment
