__base__: ../base/mmcto_drugs+summarization-diseases+summarization-only_diseases+summarization_augment-cos-loss_aux-loss-share-fc.yaml

trainer:
    logger:
        init_args:
            tags:
                pre_item: mmcto_augment
