__base__:
    - ../../../default_runtime.yaml
    - ../../../schedules/schedule_5e.yaml
    - ../../../datasets/hint/hint_phase_II_cos_schedule.yaml
    - ../../../models/mmcto/auxiliary_loss/mmcto_drugs+summarization-diseases+summarization-only_diseases+summarization_aux-loss.yaml
