__base__:
    - ../../../default_runtime.yaml
    - ../../../schedules/schedule_5e.yaml
    - ../../../datasets/hint/hint_phase_I_cos_schedule.yaml
    - ../../../models/mmcto/auxiliary_loss/mmcto_summarization-drugs-diseases-only_diseases_aux-loss-weighted-share-fc.yaml
