__base__:
    - ../../../default_runtime.yaml
    - ../../../schedules/schedule_1x.yaml
    - ../../../datasets/ctod/ctod_phase_III.yaml
    - ../../../models/mmcto/base/mmcto_aux-loss.yaml

trainer:
    logger:
        init_args:
            tags:
             - ctod_with-aux_phase_III
