__base__: ../base/mmcto_drugs+summarization-diseases+summarization-only_diseases+summarization_aux-loss-weighted-share-fc.yaml

trainer:
    logger:
        init_args:
            tags:
                pre_item: mmcto_auxiliary_loss
