__base__: ../base/mmcto_summarization-drugs-diseases-only_diseases_aux-loss-weighted-share-fc.yaml

trainer:
    logger:
        init_args:
            tags:
                pre_item: mmcto_auxiliary_loss
