__base__:
    - ../../../default_runtime.yaml
    - ../../../schedules/schedule_5e.yaml
    - ../../../datasets/hint/hint_phase_III_cos_schedule.yaml
    - ../../../models/mmcto/single_modal/mmcto_drugs+summarization-only_moe-mean.yaml
