__base__:
    - ../../../default_runtime.yaml
    - ../../../schedules/schedule_5e.yaml
    - ../../../datasets/hint/hint_phase_II_cos_schedule.yaml
    - ../../../models/mmcto/single_modal/mmcto_smiless-only_moe-mean.yaml
