__base__:
    - ../../../default_runtime.yaml
    - ../../../schedules/schedule_5e.yaml
    - ../../../datasets/hint/hint_phase_I_cos_schedule.yaml
    - ../../../models/mmcto/single_modal/mmcto_diseases-only_moe-mean.yaml
