__base__: ../base/mmcto_drugs+summarization-diseases+summarization-only_diseases+summarization.yaml

trainer:
    logger:
        init_args:
            tags:
                pre_item: mmcto_moe_method
