model:
    init_args:
        evaluator_cfg:
            class_path: torchmetrics.MetricCollection
            init_args:
                metrics:
                    PR-AUC:
                        class_path: torchmetrics.AveragePrecision
                        init_args:
                            task: binary
                    F1:
                        class_path: torchmetrics.F1Score
                        init_args:
                            task: binary
                    ROC-AUC:
                        class_path: torchmetrics.AUROC
                        init_args:
                            task: binary

trainer:
    callbacks:
        change_item:
            - - 0
              - init_args:
                    monitor: val/F1
                    filename: "epoch:{epoch}-val_f1:{val/F1:.4g}-val_pr_auc:{val/PR-AUC:.4g}-val_roc_auc:{val/ROC-AUC:.4g}.ckpt"
                    mode: max
