__base__:
    - ../../default_runtime.yaml
    - ../../schedules/schedule_1x.yaml
    - ../../datasets/ctod/ctod_phase_III.yaml
    - ../../models/mmf/middle_fusion.yaml

trainer:
    logger:
        init_args:
            tags:
             - ctod_early_phase_III
