__base__:
    - ../../default_runtime.yaml
    - ../../schedules/schedule_1x.yaml
    - ../../datasets/ctod/ctod_phase_III.yaml
    - ../../models/mmf/late_fusion.yaml

trainer:
    logger:
        init_args:
            tags:
             - ctod_late_phase_III
