__base__:
    - ../../../default_runtime.yaml
    - ../../../schedules/schedule_5e.yaml
    - ../../../datasets/hint/hint_phase_II_cos_schedule_augment.yaml
    - ../../../models/mmcto/no-summarization/mmcto_no-summarization_augment-cos-loss_aux-loss.yaml
