model:
    init_args:
        model:
            init_args:
                augment_prob:
                    table: 0.5
                    summarization: 0.5
                    smiless: 0.5
                    description: 0.5
                    drugs: 0.5
                    disease: 0.5
