model:
    class_path: lightning_template.LightningModule
    init_args:
        model:
            class_path: project.models.MMCTO
            init_args:
                encoders:
                    class_path: torch.nn.ModuleDict
                    init_args:
                        modules:
                            table:
                                class_path: torch.nn.TransformerEncoder
                                init_args:
                                    encoder_layer:
                                        class_path: torch.nn.TransformerEncoderLayer
                                        init_args:
                                            d_model: 128
                                            nhead: 2
                                            activation: relu
                                            batch_first: true
                                    num_layers: 2
                            summarization:
                                class_path: torch.nn.TransformerEncoder
                                init_args:
                                    encoder_layer:
                                        class_path: torch.nn.TransformerEncoderLayer
                                        init_args:
                                            d_model: 128
                                            nhead: 2
                                            activation: relu
                                            batch_first: true
                                    num_layers: 2
                            smiless:
                                class_path: torch.nn.TransformerEncoder
                                init_args:
                                    encoder_layer:
                                        class_path: torch.nn.TransformerEncoderLayer
                                        init_args:
                                            d_model: 128
                                            nhead: 2
                                            activation: relu
                                            batch_first: true
                                    num_layers: 2
                            description:
                                class_path: torch.nn.TransformerEncoder
                                init_args:
                                    encoder_layer:
                                        class_path: torch.nn.TransformerEncoderLayer
                                        init_args:
                                            d_model: 128
                                            nhead: 2
                                            activation: relu
                                            batch_first: true
                                    num_layers: 2
                            drugs:
                                class_path: torch.nn.TransformerEncoder
                                init_args:
                                    encoder_layer:
                                        class_path: torch.nn.TransformerEncoderLayer
                                        init_args:
                                            d_model: 128
                                            nhead: 2
                                            activation: relu
                                            batch_first: true
                                    num_layers: 2
                            disease:
                                class_path: torch.nn.TransformerEncoder
                                init_args:
                                    encoder_layer:
                                        class_path: torch.nn.TransformerEncoderLayer
                                        init_args:
                                            d_model: 128
                                            nhead: 2
                                            activation: relu
                                            batch_first: true
                                    num_layers: 2
                final_input_parts: [table, smiless, description]
                gate_input_parts: [drugs, disease]
                # augment_prob:
                #     table: 0.5
                #     summarization: 0.5
                #     smiless: 0.5
                #     description: 0.5
                #     drugs: 0.5
                #     disease: 0.5
                vocab_size: 28996
                model_dim: 128
