__base__: ../../metrics/classification.yaml

data:
    class_path: lightning_template.LightningDataModule
    init_args:
        dataset_cfg:
            split_info:
                split_format_to: [ann_file_name]
                split_name_map:
                    fit: train
                    val: valid
                    test: test
                    predict: test
            fit:
                class_path: project.datasets.CTODataset
                init_args:
                    ann_file_name: phase_I_${split}
                    data_root: data/labeling
                    augment: true
            val:
                - class_path: project.datasets.HINTDataset
                  init_args:
                      data_root: data/clinical-trial-outcome-prediction/data
                - init_args:
                      ann_file_name: phase_I_test
            # val:
            #     class_path: project.datasets.HINTDataset
            #     init_args:
            #         ann_file_name: phase_I_test
            #         data_root: data/clinical-trial-outcome-prediction/data
            #         augment: true

        dataloader_cfg:
            batch_size: 1
            # num_workers: 8
            # persistent_workers: true
            prefetch_factor: 2
            # pin_memory: true

trainer:
    logger:
        init_args:
            tags:
                pre_item: CTOD_phase_I_new
