__base__: ctod_phase_I.yaml

data:
    init_args:
        dataset_cfg:
            fit:
                init_args:
                    ann_file_name: phase_II_${split}
            val:
                change_item:
                    - - 1
                      - init_args:
                            ann_file_name: phase_II_test

trainer:
    logger:
        init_args:
            tags:
                pre_item: CTOD_phase_II_new
