__base__:
    - ../../../default_runtime.yaml
    - ../../../schedules/schedule_5e.yaml
    - ../../../datasets/hint/hint_phase_III_cos_schedule.yaml
    - ../../../models/mmcto/moe_method/mmcto_summarization-drugs-diseases-only_diseases_moe-concat.yaml
