__base__: mmcto.yaml

model:
    init_args:
        model:
            init_args:
                final_input_parts: [summarization, diseases]
                gate_input_parts: [drugs, description, smiless]
