__base__: mmcto.yaml

model:
    init_args:
        model:
            init_args:
                final_input_parts: [drugs_summarization, diseases_summarization]
                gate_input_parts: [diseases_summarization]
