__import__:
    encoder: &encoder
        class_path: torch.nn.TransformerEncoder
        init_args:
            encoder_layer:
                class_path: torch.nn.TransformerEncoderLayer
                init_args:
                    d_model: 128
                    nhead: 128
                    activation: relu
                    batch_first: true
            num_layers: 2

model:
    class_path: project.models.LightningModule
    init_args:
        model:
            class_path: project.models.MMCTO
            init_args:
                encoders:
                    class_path: torch.nn.ModuleDict
                    init_args:
                        modules:
                            table: *encoder
                            summarization: *encoder
                            smiless: *encoder
                            description: *encoder
                            drugs: *encoder
                            diseases: *encoder
                            smiless_summarization: *encoder
                            drugs_summarization: *encoder
                            diseases_summarization: *encoder
                final_input_parts: [table, smiless, description]
                gate_input_parts: [drugs, diseases]
                # augment_prob:
                #     table: 0.5
                #     summarization: 0.5
                #     smiless: 0.5
                #     description: 0.5
                #     drugs: 0.5
                #     diseases: 0.5
                vocab_size: 28996
                model_dim: 128
