__base__: mmcto_summarization-drugs-diseases-criteria-only_diseases.yaml

model:
    init_args:
        model:
            init_args:
                aux_loss_parts: [summarization, drugs, diseases, criteria]
