__base__: mmcto_drugs+summarization-diseases+summarization-only_diseases+summarization.yaml

model:
    init_args:
        model:
            init_args:
                aux_loss_parts: [drugs_summarization, diseases_summarization]
