__base__: mmcto_drugs+summarization-diseases+summarization-only_diseases+summarization_aux-loss.yaml

model:
    init_args:
        model:
            init_args:
                weighted_aux_loss: true
