data:
    init_args:
        dataset_cfg:
            fit:
                init_args:
                    tokenizer: dmis-lab/biobert-base-cased-v1.1-mnli
                    data_prefix:
                        data_path: ""
                        table_path: text_description_anypredict/processed
                        drug_description_path: drugbank/drugbank_database.json
                    max_lengths:
                        table: 512
                        smiless: 512
                        description: 512
                        drugs: 64
                        diseases: 64
            val:
                change_item:
                    - - 0
                      - init_args:
                            tokenizer: dmis-lab/biobert-base-cased-v1.1-mnli
                            data_prefix:
                                data_path: ""
                                table_path: text_description_anypredict/processed
                                drug_description_path: drugbank/drugbank_database.json
                            max_lengths:
                                table: 512
                                smiless: 512
                                description: 512
                                drugs: 64
                                diseases: 64
                    - - 1
                      - init_args:
                            tokenizer: dmis-lab/biobert-base-cased-v1.1-mnli
                            data_prefix:
                                data_path: ""
                                table_path: text_description_anypredict/processed
                                drug_description_path: drugbank/drugbank_database.json
                            max_lengths:
                                table: 512
                                smiless: 512
                                description: 512
                                drugs: 64
                                diseases: 64
            test:
                init_args:
                    tokenizer: dmis-lab/biobert-base-cased-v1.1-mnli
                    data_prefix:
                        data_path: ""
                        table_path: text_description_anypredict/processed
                        drug_description_path: drugbank/drugbank_database.json
                    max_lengths:
                        table: 512
                        smiless: 512
                        description: 512
                        drugs: 64
                        diseases: 64
