__base__: hint_phase_I.yaml

data:
    init_args:
        dataset_cfg:
            fit:
                init_args:
                    ann_file_name: phase_II_${split}
            val:
                change_item:
                    - - 0
                      - init_args:
                            ann_file_name: phase_II_${split}
                    - - 1
                      - init_args:
                            ann_file_name: phase_II_test
            test:
                init_args:
                    ann_file_name: phase_II_${split}

trainer:
    logger:
        init_args:
            tags:
                pre_item: hint_phase_II
