__base__: hint_phase_I.yaml

data:
    init_args:
        dataset_cfg:
            fit:
                init_args:
                    ann_file_name: phase_III_${split}
            val:
                change_item:
                    - - 1
                      - init_args:
                            ann_file_name: phase_III_test

trainer:
    logger:
        init_args:
            tags:
                pre_item: hint_phase_III
