__base__:
    - hint_phase_I.yaml
    - accumulate_grad_batches_patch.yaml

optimizer_config:
    lr_scheduler:
        scheduler:
            init_args:
                T_max: 164
        interval: step
