__base__: ../mmcto.yaml

model:
    init_args:
        model:
            init_args:
                moe_method: mean
                final_input_parts: [diseases]

trainer:
    logger:
        init_args:
            tags:
                pre_item: mmcto_single_modal
