name: mmcto_hint_phase_I_summarization-no-table_augment_fixed-lr_5e
method: random
program: cli
parameters:
    model/init_args/model/init_args/aux_loss_share_fc:
        values: [true, false]
    model/init_args/model/init_args/weighted_aux_loss:
        values: [true, false]
    model/init_args/model/init_args/aux_loss_parts:
        values: [[summarization, smiless, description], []]
    model/init_args/ckpt_path:
        values:
            - work_dirs/mmcto_summarization-no-table_ct-gov_1x/2023-09-15_21-58-49.547099/checkpoints/last.ckpt
            - ""
command:
    - ${env}
    - "cli"
    - "fit"
    - "--config"
    - "configs/runs/mmcto/mmcto_hint_phase_I_summarization-no-table_augment_5e.yaml"
    - "--json-file"
    - ${args_json_file}
