name: multi_modal_clinical_trial_outcome
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.12.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.9.18
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023d
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
    - absl-py==2.1.0
    - accelerate==0.26.1
    - accessible-pygments==0.0.4
    - addict==2.4.0
    - aiohttp==3.9.1
    - aiosignal==1.3.1
    - alabaster==0.7.16
    - antlr4-python3-runtime==4.9.3
    - anyascii==0.3.2
    - appdirs==1.4.4
    - argcomplete==3.1.6
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - astroid==3.0.2
    - async-timeout==4.0.3
    - attrs==23.2.0
    - babel==2.14.0
    - beautifulsoup4==4.12.3
    - build==1.0.3
    - cachetools==5.3.2
    - certifi==2023.11.17
    - cffi==1.16.0
    - cfgv==3.4.0
    - chardet==5.2.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - colorama==0.4.6
    - commitizen==3.13.0
    - contourpy==1.2.0
    - copulas==0.7.0
    - coverage==7.4.0
    - ctgan==0.8.0
    - cycler==0.12.1
    - datasets==2.16.1
    - decli==0.6.1
    - dill==0.3.7
    - distlib==0.3.8
    - distro==1.9.0
    - docker-pycreds==0.4.0
    - docstring-parser==0.15
    - docutils==0.20.1
    - et-xmlfile==1.1.0
    - exceptiongroup==1.2.0
    - faker==19.13.0
    - filelock==3.13.1
    - fonttools==4.47.2
    - frozenlist==1.4.1
    - fsspec==2023.10.0
    - gdown==5.0.0
    - gensim==4.3.2
    - gitdb==4.0.11
    - gitpython==3.1.41
    - google-auth==2.26.2
    - google-auth-oauthlib==1.2.0
    - googletrans==2.4.0
    - grpcio==1.60.0
    - huggingface-hub==0.20.3
    - icd10-cm==0.0.5
    - identify==2.5.33
    - idna==3.6
    - imagesize==1.4.1
    - importlib-metadata==6.11.0
    - importlib-resources==6.1.1
    - iniconfig==2.0.0
    - jinja2==3.1.3
    - joblib==1.3.2
    - jsonargparse==4.27.2
    - jsonnet==0.20.0
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - kiwisolver==1.4.5
    - liac-arff==2.5.0
    - lightning==2.1.3
    - lightning-template==1.6.6
    - lightning-utilities==0.10.1
    - livereload==2.6.3
    - logmatic-python==0.1.7
    - loguru==0.7.2
    - markdown==3.5.2
    - markdown-it-py==3.0.0
    - markupsafe==2.1.4
    - matplotlib==3.8.2
    - mdit-py-plugins==0.4.0
    - mdurl==0.1.2
    - minio==7.2.3
    - mmengine==0.10.2
    - multidict==6.0.4
    - multiprocess==0.70.15
    - myst-parser==2.0.0
    - networkx==3.2.1
    - nltk==3.8.1
    - nodeenv==1.8.0
    - numpy==1.26.3
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - objprint==0.2.3
    - omegaconf==2.3.0
    - openai==0.28.0
    - opencv-python==4.9.0.80
    - openml==0.14.2
    - openpyxl==3.1.2
    - orjson==3.9.12
    - packaging==23.2
    - pandas==1.5.3
    - pillow==10.2.0
    - platformdirs==4.1.0
    - pluggy==1.3.0
    - pre-commit==3.6.0
    - prompt-toolkit==3.0.36
    - promptehr==0.0.6
    - protobuf==4.23.4
    - psutil==5.9.8
    - pyarrow==15.0.0
    - pyarrow-hotfix==0.6
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pycryptodome==3.20.0
    - pydata-sphinx-theme==0.15.2
    - pygments==2.17.2
    - pyparsing==3.1.1
    - pyproject-api==1.6.1
    - pyproject-hooks==1.0.0
    - pysocks==1.7.1
    - pytest==7.4.4
    - pytest-cov==4.1.0
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytorch-lightning==2.1.3
    - pytrial==0.0.6
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - questionary==2.0.1
    - rdkit==2023.9.4
    - rdt==1.9.1
    - reconplogger==4.13.0
    - referencing==0.32.1
    - regex==2023.12.25
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rich==13.7.0
    - rpds-py==0.17.1
    - rsa==4.9
    - ruyaml==0.91.0
    - safetensors==0.4.1
    - scikit-learn==1.4.0
    - scipy==1.12.0
    - sdmetrics==0.6.0
    - seaborn==0.13.1
    - sentry-sdk==1.39.2
    - setproctitle==1.3.3
    - shell-command-launcher==1.1.0
    - six==1.16.0
    - smart-open==6.4.0
    - smmap==5.0.1
    - snowballstemmer==2.2.0
    - soupsieve==2.5
    - speed-benchmark==1.1.1
    - sphinx==7.2.6
    - sphinx-autoapi==3.0.0
    - sphinx-autobuild==2021.3.14
    - sphinx-book-theme==1.1.0
    - sphinx-design==0.5.0
    - sphinxcontrib-applehelp==1.0.8
    - sphinxcontrib-devhelp==1.0.6
    - sphinxcontrib-htmlhelp==2.0.5
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.7
    - sphinxcontrib-serializinghtml==1.1.10
    - tensorboard==2.15.1
    - tensorboard-data-server==0.7.2
    - termcolor==2.4.0
    - textaugment==2.0.0
    - textblob==0.17.1
    - thop==0.1.1-2209072238
    - threadpoolctl==3.2.0
    - tokenizers==0.15.1
    - tomli==2.0.1
    - tomlkit==0.12.3
    - torch==1.13.1
    - torch-tb-profiler==0.4.3
    - torchmetrics==1.3.0.post0
    - tornado==6.4
    - tox==4.12.1
    - tqdm==4.66.1
    - transformers==4.37.0
    - transtab==0.0.5
    - trial2vec==0.1.0
    - typeshed-client==2.4.0
    - typing-extensions==4.9.0
    - urllib3==2.1.0
    - virtualenv==20.25.0
    - viztracer==0.16.1
    - wandb==0.16.2
    - wcwidth==0.2.13
    - werkzeug==3.0.1
    - wget==3.2
    - xgboost==2.0.3
    - xmltodict==0.13.0
    - xxhash==3.4.1
    - yapf==0.40.2
    - yarl==1.9.4
    - zipp==3.17.0
