__base__:
    - ../../../default_runtime.yaml
    - ../../../schedules/schedule_3x.yaml
    - ../../../datasets/hint/hint_phase_I_augment.yaml
    - ../../../models/mmcto/base/mmcto_augment-cos-loss_aux-loss.yaml
