__base__:
    - ../../../default_runtime.yaml
    - ../../../schedules/schedule_2x.yaml
    - ../../../datasets/hint/hint_phase_III_augment.yaml
    - ../../../models/mmcto/base/mmcto_augment-cos-loss_aux-loss-share-fc.yaml
