__base__:
    - ../../../default_runtime.yaml
    - ../../../schedules/schedule_5e.yaml
    - ../../../datasets/hint/hint_phase_II_cos_schedule_augment.yaml
    - ../../../models/mmcto/base/mmcto_augment.yaml
