__base__:
    - ../../../default_runtime.yaml
    - ../../../schedules/schedule_3x.yaml
    - ../../../datasets/hint/hint_phase_II_augment.yaml
    - ../../../models/mmcto/base/mmcto_augment_aux-loss.yaml
