__base__:
    - ../../../default_runtime.yaml
    - ../../../schedules/schedule_1x.yaml
    - ../../../datasets/ctod/ctod_phase_I_augment.yaml
    - ../../../models/mmcto/base/mmcto_augment_aux-loss.yaml
