__base__:
    - ../../../default_runtime.yaml
    - ../../../schedules/schedule_5e.yaml
    - ../../../datasets/hint/hint_phase_II_cos_schedule.yaml
    - ../../../models/mmcto/base/mmcto_summarization-drugs-diseases-description-only_diseases.yaml

model:
    init_args:
        model:
            init_args:
                moe_method: mean
